benchmarks:
  -
    baseline: 65
    batch: 833334
    name: hello world
    output: a0b65939670bc2c010f4d5d6a0b3e4e4590fb92b
    src: samples/hello.b

  -
    name: semihash
    src: samples/semihash.b
    input: samples/semihash.in
    output: da39a3ee5e6b4b0d3255bfef95601890afd80709
    batch: 833334
    baseline: 72

  -
    name: harmonic
    src: samples/harmonic.b
    output: b6589fc6ab0dc82cf12099d1c2d40ab994e8410c
    batch: 71943
    baseline: 9519

  -
    name: 8 bit cell size
    src: samples/cell_size.b
    width: 8
    output: 94cfcfa4ce6f757b8211ef5a2882076d7fc4f7bd
    batch: 909091
    baseline: 39

  -
    name: 16 bit cell size
    src: samples/cell_size.b
    width: 16
    output: d2bb3c52eaf4286637d9a3df1e6024c2aaeb7728
    batch: 416667
    baseline: 1222

  -
    name: 32 bit cell size
    src: samples/cell_size.b
    width: 32
    output: 85c954c43002504b11cc5e239de7c6d0cc96e522
    batch: 294118
    baseline: 2347

  -
    name: mandlebrot
    src: samples/mandlebrot.b
    output: b77a017f811831f0b74e0d69c08b78e620dbda2b
    batch: 2
    baseline: 675535550
